name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: cd apps/frontend && npm ci 
      - run: cd apps/frontend && npm run lint
      - run: cd apps/frontend && npm run typecheck
      - run: cd apps/frontend && npm run build

# name: CI

# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]

# jobs:
#   frontend:
#     name: Build Frontend
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 18
#           cache: 'npm'
#       - run: cd apps/frontend && npm ci
#       - run: cd apps/frontend && npm run lint
#       - run: cd apps/frontend && npm run typecheck
#       - run: cd apps/frontend && npm run build

#   backend:
#     name: Build Backend
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 18
#           cache: 'npm'
#       - run: cd apps/backend && npm ci
#       - run: cd apps/backend && npm run lint
#       - run: cd apps/backend && npm run typecheck
#       - run: cd apps/backend && npm run build
